### ISSUE TITLE
Edge has a storage limit of 1MB per value

### ISSUE THREAD

**Issue by nikrolls** [nikrolls/uBlock-Edge#1]
There is an issue caching definitions because the cache value exceeds the Edge limit of 1MB per value.
https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/api-support/supported-apis/

This is an unhandled exception and is causing issues loading lists. It may "just work" if we handle the exception (even though it's not an optimal solution).

**Comment by gorhill** [comment]
On ABP's issue tracker, there [an entry for the storage limit issue](https://issues.adblockplus.org/ticket/4023). One of the developer comments:

> there is also a limit of total 5Mb storage per extension it looks like we will have to move away from the `chrome.storage.local`.

The 5MB-per-extension limit, is this something you have also observed?

**Comment by nikrolls** [comment]
I haven't run into this issue, and can't actually see it documented (unless it's been added very recently). I'll do some investigation though.

I found that splitting into 1MB chunks didn't work either. I ended up having to use 300KB chunks, a limit I found through trial and error.

**Comment by sloppy9** [comment]
For an alternative to local storage, consider using [https://github.com/localForage/localForage](https://github.com/localForage/localForage).

**Comment by gorhill** [comment]
In case you didn't see this, I just found that Mozilla is providing great reference documentation about the WebExtensions API, including detailed cross-browser compatibility (Edge is documented in there): <https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs>.
