### ISSUE TITLE
Cannot full support Domain restrictive Inverse type options

### ISSUE THREAD

**Issue by lychichem** [nikrolls/uBlock-Edge#101]
### Describe the issue
ublock edge cannot full support Domain restrictive Inverse type options

### One or more specific URLs where the issue occurs
https://weibo.com/ (Maybe an account is needed)

### Screenshot in which the issue can be seen
Bad:
![bad](https://user-images.githubusercontent.com/9316590/34905549-c48bd332-f895-11e7-804c-97fee91d14e7.PNG)
Good:
![good](https://user-images.githubusercontent.com/9316590/34905550-cd02449c-f895-11e7-98ef-9aa0f7525c7a.PNG)

### Steps for anyone to reproduce the issue
1. Install a custom filter from https://raw.githubusercontent.com/523860169/list/master/ad.txt
2. Open weibo.com
3. Many functions relates to js.t.sinajs.cn/open/analytics/js/suda.js will not work. The screenshoot above show one of them, that is, the emoji panel will be in bad mode. (althouth there is actually a whitelist `@@||sinajs.cn/open/analytics/js/suda.js$domain=weibo.com|~widget.weibo.com`)
4. Add a custom whitelist @@||sinajs.cn/open/analytics/js/suda.js$domain=weibo.com
5. All function at weibo.com will work fine.

### Your settings
Only use filter above and cancel other filters.

- OS/version: Windows 10 x64 build 16299.162 pro version
- Browser/version: Microsoft Edge 16.16299
- uBlock Origin version: 1.14.23

##### Your filter lists
No

##### Your custom filters (if any)
https://raw.githubusercontent.com/523860169/list/master/ad.txt

**Comment by lychichem** [comment]
@523860169 I've submitted the issue I talked with you just now here, is there anything I forgot to say here? Or did I say something wrong? Please give additional information if needed.

**Comment by gorhill** [comment]
It's a problem in uBO core it seems, I will fix asap.

**Comment by lychichem** [comment]
@gorhill Thanks for your fix. I've sideloaded your fix version of ublock and see it works as expected. Now it's time for @nikrolls to merge.

**Comment by nikrolls** [comment]
@lychichem, can you please confirm if this is fixed in 1.14.24?

**Comment by lychichem** [comment]
@nikrolls Yes, it was fixed on 1.14.24.
