### ISSUE TITLE
There's no third-party filters to select

### ISSUE THREAD

**Issue by jppmarujo** [nikrolls/uBlock-Edge#107]
### Describe the issue

I'm using uBlock Origin on Chrome, which works without any hiccups. 
So i tried installing it on Microsoft Edge. 

There is no 3rd party filters list to choose from, which makes the surfing the web less enjoyable, since there are still a lot of annoyances active, like Anti-Adblocks or pop-under ads.

### One or more specific URLs where the issue occurs

ms-browser-extension://EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62/dashboard.html#3p-filters.html

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/32954931/36399808-7fd7cf3c-15c5-11e8-8471-6b9c798866ba.png)

### Steps for anyone to reproduce the issue

1. Click Edge three dots;
2. Choose Extensions;
3. Click the uBlock Origin gear;
4. Choose Options;
5. Navigate to 3rd party filters tab.

### Your settings

- OS/version: 10.0.17604 · Version 1809 · Redstone 5 
- Browser/version: Microsoft Edge 42.17604.1000.0
- uBlock Origin version: 1.15.4

##### Your filter lists

None, that's what i'm looking for.

**Comment by jppmarujo** [comment]
Somehow it started to work, and i don't think the extension updated within the Microsoft Store.
In my specific case, it is closed, you may want to close the issue. Nonetheless, it happened, so you might look into it if you have the time.

**Comment by nikrolls** [comment]
Thanks @jppmarujo. This is an odd case and I'm glad it resolved itself. I'll close the issue as it's fixed for you, but it will be on record should someone else have the same issue and wishes to re-open it.

**Comment by RamRS** [comment]
I have this problem too. Same steps to reproduce as the OP, here is the screenshot and my environment details:

**Screenshot in which issue can be seen**:

***

![Screenshot](https://image.ibb.co/gL7jjp/image.png)

***

**Steps for anyone to reproduce the issue**:

 1. On any webpage, click on uBlock Origin icon
 2. Click on the "Open the Dashboard" icon (highlighted here: <img alt="screenshot" src="https://image.ibb.co/hJcH4p/Screen_Shot_2018_09_14_at_11_56_14_AM.png" width="300px">)
3. Try to Navigate to "3rd Party Filters" tab

***

**Your settings**:

 - OS/Version: macOS High Sierra 10.13.6
 - Browser/Version: Google Chrome Version 69.0.3497.92 (Official Build) (64-bit)
- uBlock Origin Version: v1.16.18
