### ISSUE TITLE
uBlock0.edge-1.8.5b0 Displaying different version in extension information pane

### ISSUE THREAD

**Issue by arebee** [nikrolls/uBlock-Edge#11]
### Describe the issue
In Edge, inspect the information for uBlock Edge 1.8.5b0. It shows 1.7.7. This is because `manifest.json` has "version": "1.7.7" rather than "version": "1.8.5b0"

### One or more specific URLs where the issue occurs

n/a 

### Screenshot in which the issue can be seen

![bad version](https://cloud.githubusercontent.com/assets/3378805/17985283/fd893b08-6ac9-11e6-9a4d-4639421f412a.png)

### Steps for anyone to reproduce the issue

1. Enable extensions in Edge, load 1.8.5b0.
1. Inspect information about the extension by clicking on it.
1. Version string doesn't match the build.

### Your settings

Default. None changed.

- Browser/version: Microsoft Edge 38.14393.0.0; Microsoft EdgeHTML 14.14393
- uBlock Origin version: uBlock0.edge-1.8.5b0

##### Your filter lists

Default filter lists.

##### Your custom filters (if any)
None.

**Comment by nikrolls** [comment]
Thanks @arebee, this is fixed in the latest releases.
