### ISSUE TITLE
[FYI] Edge layout engine bug filed

### ISSUE THREAD

**Issue by jspenguin2017** [nikrolls/uBlock-Edge#115]
### Describe the issue

An Edge layout engine bug cause subsequent-sibling combinator to not get recalculated for (only) local files. 

I have filed an issue here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17473318/

### One or more specific URLs where the issue occurs

Dashboard.

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/7283682/39904845-5e4a63e6-5497-11e8-9da7-14e4f866843f.png)

I have a duct tape for it, do you need a PR? 
![image](https://user-images.githubusercontent.com/7283682/39904909-ca3b05ce-5497-11e8-9308-de1c03c7f7ef.png)

**Comment by reunicorn** [comment]
Good news! According to James M. of the MS Edge Dev Team, 

> this feature is fixed in Edge 17134.

That's the version which comes with the April 2018 Update, aka RS5.

**Comment by nikrolls** [comment]
Thanks for following this up, @reunicorn!
