### ISSUE TITLE
[Documentation Request] Development Status

### ISSUE THREAD

**Issue by mvastola** [nikrolls/uBlock-Edge#12]
Hi,
Just a quick/simple documentation request. 
I have a strictly monogamous relationship with Linux, so I am unable to try out your extension (though I do use the upstream version of uBO on FF). 

Anywho, I just wrote a uBO filter list I'd like to share with others. In addition to the standalone list, I was going to provide documentation on how to install uBO for the various major browsers, and upon seeing that your Edge fork existed, I was considering including that one. My only hesitation is that it's not immediately clear what the development status is of this edition of the extension.

According to the [upstream README](/gorhill/uBlock/blob/master/README.md#microsoft-edge), this is in "early development". You've chosen to mirror the upstream version numbers, however, and "early development" doesn't convey either the degree of feature parity, nor the stability of the implemented features. (There's also no alpha or beta designation that's immediately visible.) I was hoping you might be able to clarify.

I would also suggest summarizing any stability issues/missing features (compared to upstream) on the README, since I'm not alone with this question.

Thanks a bunch.

**Comment by nikrolls** [comment]
Hi @mvastola, sorry for the delay in responding. I've been actively working on this project but didn't get back to this as soon as I could have.

I have been very intentional in stating that this is pre-release. The documentation on both repos says so, and the releases are all tagged 'Pre-release' using the semver pre-release notation (`-edge`, while I agree it's not so obvious, is technically a pre-release notation in semver). Once I begin to make stable releases I will drop the `-edge` notation (because in the context of this repo it's not needed) and I will tag the releases as stable. They will also be released in the Windows Store at this point.

I'm open to suggestions here; at the very least I will change the pre-release notation to something like `-pre+edge`, where the hyphen notation indicates pre-release and the plus notation indicates build metadata.

With regards to stability issues or missing features, they are all listed in this repo's issue tracker. I'm not keen on maintaining a separate summary because as with all documentation it will become out of date extremely quickly.

**Comment by mvastola** [comment]
Ah. The `-edge` notation in semver is indeed confusing in this context, but that isn't immediately visible upon first glance of the repo in any case so I think something more prominent might be desirable.

Might I suggest specifying "alpha"/"beta"/"pre-release"/etc in the subtitle of the repo (if it fits) as well as updating to the `README.md`? I totally understand not wanting to have to maintain a list of missing/incomplete features, but right now you don't even mention that any incomplete features might exist, and there is a bit of useless/irrelevant information.

Some of some of the unnecessary cruft from the upstream `README.md` in this fork I would suggest deleting (or replacing with a link it's location in the upstream file):

- It would seem that the performance/benchmarking section is premature as it applies to Microsoft Edge. Unless/until you have benchmarks, you have no idea if ABP is slower. Also, if this is still in pre-release, it's probably not totally optimized for speed. In any case, unless you have an analogous graph for Microsoft Edge, I would just write a couple of sentences that say the algorithm that this extension uses has proven to be faster than ABP's in Chrome and FF and include a link to the performance anchor in the upstream `README.md`.
- There's no need for installation instructions for other browsers in this repo. Just link people to upstream if they want the extension on other browsers.
- Many links in the TOC are broken (they link to anchors that don't exist in this version) a Nd should be pruned.
- The translations should be removed as they are not translations of the Edge extension but of the upstream version.

I would also suggest prepending your `README.md` with a section describing this edition of the extension that states:
- This is a fork for the Microsoft Edge browser.
- It is a pre-release version and eschews promises of total stability in favor of an attempt at feature parity with the upstream repository.
- Known missing/broken/buggy features are listed/described on the issues (insert link) page.
- If you run into an issue not listed, please submit it (insert link) with relevant details (provide link to issue submission guidelines or set up template for new issues).
- Features documented in the upstream version and not otherwise noted on the issues page are *thought to* (but are **by no means guaranteed to**) be working.

**Comment by nikrolls** [comment]
All good points. I'll re-work `README.md` with many of those recommendations, as you're right -- it should be easy to find Edge-specific information. This is something I'd planned to do but not allocated the time; now that the major issues are under control I have a chance to do it.

Regarding translations, do you mean the translation files in the extension? I can't find any reference to them in the Readme.

**Comment by mvastola** [comment]
![ublock-edge_readme md_at_master_ _nikrolls_ublock-edge_-_2016-11-08_21 44 25](https://cloud.githubusercontent.com/assets/599767/20125633/9cefffe8-a5fc-11e6-88de-355541ae7447.png)

**Comment by nikrolls** [comment]
Thanks for your feedback; I've made a major update to `README.md` and also modified the About page of the extension to point to this repo.
