### ISSUE TITLE
uBlockOrigin filters not updating on MS Edge, maybe bad URL error

### ISSUE THREAD

**Issue by CorvetteAddict** [nikrolls/uBlock-Edge#131]
### URL(s) where the issue occurs

At the control panel of uBlockOrigin for Edge, filters tab

### Describe the issue

They don't update at all, only non ublock filters update correctly. Others rest with a network error signal

### Screenshot(s)

https://imgur.com/KG4H12O

### Versions

- Browser/version: MS Edge
- uBlock Origin version: 1.15.24

### Settings

non]

### Notes

I perfectly know that the proyect is on stand by, but the problema is enough important to make a fix for the few poeople that are still using it fully updated.

Thx!

**Comment by gwarser** [comment]
Do you see these requests being blocked in The Logger?

**Comment by CorvetteAddict** [comment]
Sorry, I'm not at work at this moment, so I can verify it at night, but can you remind me where I can find this Logger, please?

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by CorvetteAddict** [comment]
Ok, I only see network errors:

https://imgur.com/aN5c2rD

Maybe is on my end, because I've tried it on another PC with Edge installed (one of my work), and it fully updated all the filters without issues.

**Comment by gwarser** [comment]
What happens if you try to open these links in browser, for example: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt?_=218591

**Comment by CorvetteAddict** [comment]
Ok, seems a problem with my home ISP that's blocking the access to those URLs because I get an 404 errors when I try to open those links.

With my mobile ISP I can access without any problem.

What can I do?

**Comment by gwarser** [comment]
"Sky Fibre" by any chance? They have something called "broadband shield", and this can be disabled somehow. I don't know how, this is info from old Reddit post https://removeddit.com/r/uBlockOrigin/comments/728m5i/unable_to_update_filters/

Can also be antivirus.

**Comment by CorvetteAddict** [comment]
OK, I have found the source of the problem. Seems that Spanish goverment have decided to block al access to raw.githubusercontent.com from any ISP inside Spain, or at least the three big ones, and my home ISP is one of them. More info:

https://twitter.com/topjohnwu/status/1194205128867209216

https://github.com/github/gov-takedowns/blob/master/Spain/2019/2019-10-23-GuardiaCivil.md

Maybe changing DSN i can bypass the block. Anyway, thanks a lot for your support, mate!

**Comment by CorvetteAddict** [comment]
Confirmed. Changing DNS fix the connection issue.
