### ISSUE TITLE
Extension load failed

### ISSUE THREAD

**Issue by Akababa** [nikrolls/uBlock-Edge#17]
When I try to lead the extension it gives me a manifest parsing error (missing or malformed manifests file). Any fixes?

**Comment by japborst** [comment]
@Akababa I saw your issue on the upstream repo as well. You did download the latest release from this repo (https://github.com/nikrolls/uBlock-Edge/releases) right? No manifest issues here.

**Comment by nikrolls** [comment]
Yes, please try the releases from this repo (eg https://github.com/nikrolls/uBlock-Edge/releases/tag/1.9.10-edge) and then let me know if you are still having issues.

**Comment by nikrolls** [comment]
Closing as there has been no response to this issue.
