### ISSUE TITLE
ublock update data bases broken. + no language selection.

### ISSUE THREAD

**Issue by mysterieworld** [nikrolls/uBlock-Edge#18]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

When choose a data base, the plugin freeze, but does not update.
You can still click on a other setting, but it will not update the data bases.

Beside of that, why you cannot choose your own language, it's using my own language. But Prefer English.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![image](https://cloud.githubusercontent.com/assets/22658784/19150774/16ac6950-8bc9-11e6-99a7-52adaaac6515.png)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Just choose a database, and apply/update

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Latest public Microsoft Edge Release
- uBlock Origin version: 1.9.11.101

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by nikrolls** [comment]
This appears to be an intermittent issue not with the build but with the installation. If you remove the extension and re-install it, there's about a 50/50 chance that it will resolve itself.

It's actually still working, and if you continue to refresh this page you will see it update. The only thing that's broken is the message from the background process to the UI telling it to update the progress bar. I'm looking into it.

**Comment by japborst** [comment]
Been investigating this today actually. It does indeed update perfectly.

It appears that the issue arises from an error of `vAPI.message.broadcast` in [vAPi-background.js](https://github.com/nikrolls/uBlock-Edge/blob/master/platform/edge/vapi-background.js). Edge throws a 'handle is invalid error' after the postMessage method is called.

**Comment by nikrolls** [comment]
The thing I find odd is that it seems to be related to the install. 25-33% of the time you get an install where this progress bar works 100% of the time. With other installs it doesn't work ever. But it never changes between installs.

**Comment by japborst** [comment]
@nikrolls Interesting. For me the behaviour was: first time it works flawlessly, afterwards it hangs. But we can say it is definitely a communication issue, so perhaps we can force it through a workaround.

Regarding language selection, @mysterieworld, this should be implemented in the original repo. However it doesn't seem it'll be here anytime soon; see [uBlock#241](https://github.com/gorhill/uBlock/issues/241). Changing your browser language will solve though.
