### ISSUE TITLE
Peter Lowe’s Ad and tracking server list breaks slack.com and duckduckgo.com

### ISSUE THREAD

**Issue by lope** [nikrolls/uBlock-Edge#26]
### Description
When **Peter Lowe’s Ad and tracking server list** is enabled, lots of sites break.

### One or more specific URLs where the issue occurs
http://duckduckgo.com/?t=lm&q=ublock+origin
http://imgur.com/
foo.slack.com (a chat group you're part of)

### Screenshot in which the issue can be seen
http://imgur.com/a/qc9Sc

### Steps for anyone to reproduce the issue
1. Enable Peter Lowe’s Ad and tracking server list
2. Visit URLs
3. Try copy my settings also.
4. Check version

### Your settings
http://imgur.com/a/WYuwa

Chromium 53.0.2785.143
- uBlock Origin version:  1.9.16

##### Your filter lists
I don't know what default is, I only enabled a few extras, in my above screenshots.

##### Your custom filters (if any)
None

**Comment by nikrolls** [comment]
This repo is for the Edge port of the extension; could you please re-file this issue at https://github.com/gorhill/uBlock/issues? 

I can understand the confusion as I haven't modified the readme much in this fork. I plan on doing that soon.

**Comment by gorhill** [comment]
> http://imgur.com/a/qc9Sc

That is not normal, Peter Lowe's is a hosts file, there is no `com` entry in it. Maybe the list did not download properly, an update should be forced by purging it in _3rd-party filters_ pane.

**Comment by lope** [comment]
Oh @gorhill, okay I updated and it seems fine now :) thanks
