### ISSUE TITLE
Ads are not blocked on bing.com web searches

### ISSUE THREAD

**Issue by pedrogarcia** [nikrolls/uBlock-Edge#30]
### Describe the issue
Bing ads do not get blocked, even when creating a filter for them. 

### One or more specific URLs where the issue occurs

https://www.bing.com/

### Steps for anyone to reproduce the issue

1. Make a web search on bing, for example: used cars

### Your settings

It is reproduceable on the default settings

- Browser/version: Microsoft Edge
- uBlock Origin version: ublock edge

##### Your filter lists

Default filter lists

**Comment by gorhill** [comment]
If you add `bing.com##.b_ad` as custom filter, does it work?

**Comment by pedrogarcia** [comment]
Nope. Not on edge, specifically. On chrome, the ads are blocked. Also, other Adblocks don't get ads blocked on bing on edge. As well. There is even a bug report opened in Adblock Plus https://issues.adblockplus.org/ticket/4425

**Comment by gorhill** [comment]
I disabled the shadow DOM code path on Chrome (which is how ads are properly hidden on `bing.com`), and I can reproduce the result of ads not being hidden (sometimes they are). There is code in uBO's content script for yet another fallback when user styles and shadow DOM are not supported, but it does not work (often) on `bing.com` because of a timing issue.

There is probably a way to fix this, I will experiment.

**Comment by nikrolls** [comment]
Thanks for jumping onboard @gorhill. When they do get through they seem to show up after a short delay, whereas with uBlock off they show instantly. So a timing issue sounds plausible.

As a quick test, I manually removed the inline `display: block !important` style from the ad element and it hid the element as expected. So the styles are being respected but only at a normal level of specificity.

**Comment by nikrolls** [comment]
This is resolved in 1.10.4, which will be available from the Store soon.

**Comment by gorhill** [comment]
@nikrolls The fix is not part of 1.10.4, as it needs more through testing before being released since how cosmetic filtering is enforced has been changed beyond trivial. Sorry for the confusion, I released 1.10.5b0 to make this clear.

**Comment by nikrolls** [comment]
Ah, ok -- no worries! I can re-jig the release to match yours (I'd rather keep it aligned). I'm preparing the Store release later today anyway, so no harm done.

Cursory testing shows that the fix appears to have resolved the issue in this ticket, so it's on the right track.

**Comment by gorhill** [comment]
Actually I thought it was nice to see the fix released for Edge, given that it still is preview mode, and that it does solve an issue which was not present on other platform -- so the risk for Edge is really non-existent. I worry more about more testing needed for Chromium and Firefox. Maybe you could create a revision 1.10.4.1 specific to Edge? (the extra ".1" would make it clear it's not exactly 1.10.4)
