### ISSUE TITLE
Ublock Origin will not block ad after change page index

### ISSUE THREAD

**Issue by kevin12314** [nikrolls/uBlock-Edge#33]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Some websites Ublock Origin will not block ad after change page index.
When this bug appear,the "block element" in context menu won't work.

### One or more specific URLs where the issue occurs

http://ck101.com/thread-2551696-19-1.html

### Screenshot in which the issue can be seen

First time it will block ad as expected
![image](https://cloud.githubusercontent.com/assets/10508800/21090210/043b56de-c079-11e6-8b5c-9840e6f83938.png)

And then change page index,Ublock Origin not work
![untitled](https://cloud.githubusercontent.com/assets/10508800/21090464/e85ebaee-c07a-11e6-8794-bdc9e0ccd2cb.png)

### Steps for anyone to reproduce the issue

1.Install ublock origin in Windows Store.
2.Set up the filter in filter lists.
3.Go to http://ck101.com/thread-2551696-19-1.html.
4.Change page index more than one time.
5.Ublock Origin will not block ad. Use Ctrl+F5 to refresh still not work. The "block element" in context menu won't work.

English isn’t my first language, so please excuse any mistakes.

### Your settings
- Browser/version: Microsoft Edge 39.14986.1000.0 (Traditional Chinese)
(about:config page settings：
![image](https://cloud.githubusercontent.com/assets/10508800/21090807/3a032112-c07d-11e6-98c7-6e90702411d8.png)

)
- uBlock Origin version: uBlock Origin v1.10.1

##### Your filter lists
+ Default filter lists 
+ Adblock Warning Removal List‎
+ Anti-Adblock Killer | Reek‎
+ Fanboy’s Annoyance List‎
+ CHN: CJX's Annoyance List‎
+ CHN: EasyList China (中文)
+ My filters‎ (
apk.tw##div#confirmOverla
ck101.com##div.adTopBox
ck101.com##div.a_cn
)
##### Your custom filters (if any)
https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/ABP-FX.txt

**Comment by nikrolls** [comment]
Thanks @kevin12314, I'll look into this shortly!

**Comment by nikrolls** [comment]
Ah ha! It looks like you're using the version from the latest Fast Ring preview. There are known issues there with cosmetic filters not working properly after the first load. This works fine in the current release version of Edge.

http://simple-adblock.com/faq/testing-your-adblocker/
