### ISSUE TITLE
tapping on icons in tablet mode selects them

### ISSUE THREAD

**Issue by wind-rider** [nikrolls/uBlock-Edge#34]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
In "tablet mode" (windows 10) the icons become selected as text when you tap on them. This makes it unclear in what state the switch is (if the icon represents a switch) and it makes the interface feel odd.

### Screenshot in which the issue can be seen
![image](https://cloud.githubusercontent.com/assets/3463496/21099660/b3b17422-c06f-11e6-8266-b0dafae532ec.png)

### Steps for anyone to reproduce the issue

For example when turning off ublock for a specific site:

1. you open the extension drop down
2. you tap the "power icon" (tap with your finger on a touch screen, this does not concern a Wacom stylus because it is treated like a mouse)
3. the icon should become grey to show that ublock is switched off, but instead it becomes selected and because of that it stays blue while actually being turned off.

### Your settings
Windows in tablet mode using on-screen keyboard (no physical keyboard attached)

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Microsoft Edge 39.14965.1001.0
- uBlock Origin version: 1.10.1 prerelease from windows store

**Comment by stkb** [comment]
Seeing this too. A couple of notes:
- It seems to only affect the large power icon. All other clickable elements seem to work ok.
- Windows doesn't have to be in tablet mode or without a keyboard; it always happens when you touch the icon instead of clicking.
- In Chrome the icon works fine although it does get selected for a fraction of a second before deselecting

**Comment by gorhill** [comment]
Adding `user-select: none;` to the button's style would probably fix the issue.

**Comment by nikrolls** [comment]
Thanks @wind-rider for the report. I think I should add a few touch-specific styles to the platform styles; @gorhill I would say `user-select: none;` would be the one.

**Comment by gorhill** [comment]
I tried `user-select: none;` in Chromium and it did prevent the selection. So this should be added to the platform-independent code. Does the style work on Edge without the `-ms-` or `-webkit-` prefix?

**Comment by nikrolls** [comment]
Yep, no prefix is fine.

**Comment by japborst** [comment]
You likely have tested this, but caniuse suggests otherwise... http://caniuse.com/#search=user-select

**Comment by wind-rider** [comment]
It also happens in the request log:
![image](https://cloud.githubusercontent.com/assets/3463496/21157156/b92020a2-c178-11e6-980c-1a3a0c6ea0d9.png)

**Comment by gorhill** [comment]
Ok, I will apply the style to all `.fa` button -- there is no real use case for being able to select these buttons.

**Comment by nikrolls** [comment]
@japborst Arg, you're right. I'm so used to using autoprefixer at work.

**Comment by nikrolls** [comment]
Thanks @gorhill; the -webkit prefix works in Edge due to their compat work. I'll close this now and work on the 1.10.2 release!
