### ISSUE TITLE
Google spams the user with large banner ads for Google Chrome

### ISSUE THREAD

**Issue by branpurn** [nikrolls/uBlock-Edge#36]
An issue Edge has that Chrome doesn't: Google spams the user with (sometimes large) banner ads for Google Chrome. Is there a way for an Edge uBlock-specific block on these?

**Comment by ctolkien** [comment]
God I hate those ads too...

**Comment by gorhill** [comment]
<https://www.youtube.com/watch?v=8TvCGWwQr5o>.

[CONTRIBUTING](https://github.com/nikrolls/uBlock-Edge/blob/master/CONTRIBUTING.md):

> For filter-related issues, report on the respective filter list support site, or at [uBlockOrigin/uAssets](https://github.com/uBlockOrigin/uAssets/issues).

**Comment by nikrolls** [comment]
Thanks @branpurn for the report. As @gorhill indicated, this is more likely a filter list issue. I would expect that Firefox users would also be getting these banner ads? So it's definitely something that could go in a global list rather than specifically in the Edge extension.
