### ISSUE TITLE
UBlock doesn't update the filter list

### ISSUE THREAD

**Issue by gofirst2220** [nikrolls/uBlock-Edge#44]
### Describe the issue
It just doesn't update certain filter list other than its own. 

### One or more specific URLs where the issue occurs
Ublock's Settings dashboard

### Screenshot in which the issue can be seen

see filter list section or here: [see](http://i.imgur.com/izQaOrx.png)
### Steps for anyone to reproduce the issue

1. Click on Settings icon on the Ublock pop up
1. Navigate to Filter List tab
1. click on "Update Filters"

### Your settings
"Advanced users" in Ublock Origin and nearly every checkbox in about:flags enabling some features such as WebRTC.

- Browser/version: 39.14986.1000.0
- uBlock Origin version: 1.10.2

##### Your filter lists
[My Filters](http://i.imgur.com/izQaOrx.png)

Default Filter Lists + Adware killers such as Easy List and malware Domains lists

**Comment by nikrolls** [comment]
Thanks @gofirst2220, I had a suspicion this may be the case. I'm going to take a look into it shortly.

**Comment by nikrolls** [comment]
@gofirst2220, I seem to be able to update everything manually. I'm currently looking into whether automatic update is working as expected.

Can you please confirm if you're experiencing the issue with manual updates as well?

**Comment by siyangqiu** [comment]
Hi! I'm not gofirst2220, but I have a similar issue. Manually clicking "Update" will get the loading bar, but at some point the loading bar will hang - leaving it will not let it go away, so it's not just slow. However, once I hit refresh, everything does show up-to-date. I've had this issue both on the store version and the sideloaded version. Anyhow, this is more of a minor issue.

**Comment by nikrolls** [comment]
Thanks @siyangqiu. I'll keep looking into it.

**Comment by nikrolls** [comment]
I'm closing this now as there have been no recent reports of the issue and the UI was re-worked since then. Feel free to open it again if there is further information.
