### ISSUE TITLE
Refresh button in uBlock panel doesn't refresh a page that has an url containing a '#'

### ISSUE THREAD

**Issue by stkb** [nikrolls/uBlock-Edge#47]
#### To reproduce: 
1. Go to a url with a hash-part, eg: https://en.wikipedia.org/wiki/UBlock_Origin#History
2. Open the uBlock panel and make a change; eg: one of the advanced filters or deactivating uBlock itself.
3. Click the refresh button that has appeared
   <img width="373" alt="ublockrefresh" src="https://cloud.githubusercontent.com/assets/6125444/21439861/75f2117c-c890-11e6-9518-1a7f53869aed.png">
4. While the button reacts and disappears, the page doesn't refresh to apply the changes. 

#### Additional info:
* While the page doesn't refresh, it acts as if you'd gone to the address bar and pressed 'enter', ie: if you first scroll up to the top of the page, it'll scroll back down to the "History" section. 
* On urls without hashes, it works fine.
* Works fine on the Chrome version.

### Settings

- Browser/version: Edge 38.14393.0.0
- uBlock Origin version: 1.10.2
- Default settings, no filter lists, no custom filters.

**Comment by stkb** [comment]
Actually the behavior is consistent with pressing enter in the address bar: for hashless urls the page always gets refreshed; for urls with a hash part it doesn't (unless the main url part before the hash has changed).

**Comment by japborst** [comment]
You're completely right, that is exactly what it does. Edge did not support the reload function (and still doesn't, just checked) and I wrote this workaround in #8. Didn't think the hashed case through, apparently.

**Comment by stkb** [comment]
Ah, yeah I see. I guess there's nothing to do until platform support comes?

(For reference: [Edge platform issue 9107382](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9107382/)).

**Comment by nikrolls** [comment]
#48 works around this issue ;)

It will still be better to use the proper API when it's supported, but until then this feels acceptable.
