### ISSUE TITLE
Can't check/uncheck settings

### ISSUE THREAD

**Issue by jack-cole** [nikrolls/uBlock-Edge#49]
### Describe the issue

Clicking the checkboxes on the settings page doesn't work. The checkboxes appear to be clicked, but they don't get checked. (they highlight black on the inside when the mouse button is held down)

### One or more specific URLs where the issue occurs

ms-browser-extension://EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62/dashboard.html

### Screenshot in which the issue can be seen

https://webmshare.com/KEJLm

### Steps for anyone to reproduce the issue

Install uBlock Origin on an Edge browser, go to the settings, and try unchecking the boxes

### Your settings

- Browser/version: Microsoft Edge 38.14393.0.0, Microsoft EdgeHTML 14.14393
- uBlock Origin version: 1.10.2

##### Your filter lists

Default filter lists 

##### Your custom filters (if any)

none

**Comment by nikrolls** [comment]
@jack-cole, is this still an issue with the latest versions of Windows and uBlock Origin?

**Comment by jack-cole** [comment]
@nikrolls In 1.15.4, the issue is no longer present.

**Comment by nikrolls** [comment]
Thanks @jack-cole!
