### ISSUE TITLE
Ads not blocked in adobe flash

### ISSUE THREAD

**Issue by Aerodog** [nikrolls/uBlock-Edge#5]
Hey, nikrolls. I've been enjoying the latest release for Edge, but found a couple of issues. Ads are _not_ blocked on twitch.tv streams **only** as long as Adobe Flash is enabled in advanced settings. Once flash is disabled, ads no longer get through (because it defaults to HTML5). 

Additionally, purging the cache for filter lists followed by updating the lists causes the tab to hang seemingly indefinitely. The task seems to complete, however, so this isn't very important.

**Comment by meetshawn** [comment]
I do not experience this issue. Twitch.tv ads definitely don't show up for me, and I have Flash enabled. 

Are you referring to initial ads shown when you open a stream, or ads initiated by the streamer during the stream?

**Comment by japborst** [comment]
Seems like a filter lists issue. Probably a good idea to list what's enabled (see: [issue guidelines](https://github.com/nikrolls/uBlock-Edge/blob/master/CONTRIBUTING.md)) . Difference between Flash/HTML5 player could be different hostnames from which the ads are served from.

**Comment by lewisje** [comment]
It can't be done: https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/tree/master/extensions/API-support/supported-APIs#webrequest

> Network requests from `<object>` and `<embed>` elements are not supported.

**Comment by nikrolls** [comment]
We can keep an eye on this API and if they implement the required functionality then it should just work.

**Comment by ghajini** [comment]
other adblockers working fine.. checked with AdBlock

**Comment by ghajini** [comment]
@nikrolls `webrequest` api is supported as of  — Microsoft Edge (38) / Windows 10 (14393)

ref link 
`https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap`
