### ISSUE TITLE
The 3-rd party filters list is gone, ads aren't being blocked

### ISSUE THREAD

**Issue by dsrtfx** [nikrolls/uBlock-Edge#55]
Turned on my computer this morning, went to YouTube to watch videos, and realized that no ads were getting blocked anymore. Went to the options, and saw that the list is gone (see attached screenshot), no subscriptions to any lists.

I reset to default settings, but the 3rd party list is still gone.

I installed the uBlock Origin for Edge extension from the MS Store yesterday, it was working great yesterday.

![untitled](https://cloud.githubusercontent.com/assets/7445259/22070448/ac7364f4-dd61-11e6-9bd9-012b407d16e2.png)

### Your settings

- Browser/version: Microsoft Edge 38.14393.0.0
- uBlock Origin version: uBlock Origin v1.10.2

**Comment by mrabinovsky** [comment]
I will confirm this problem. Also clicking on the uBlock logo no longer opens the menu for me. I've tried uninstalling and reinstalling from the app store.

**Comment by vemacs** [comment]
See https://github.com/nikrolls/uBlock-Edge/issues/59

**Comment by nikrolls** [comment]
Hi @dsrtfx and @mrabinovsky, could you please check if the latest version is working for you? 🏷 1.11.2.

**Comment by mrabinovsky** [comment]
I can confirm that the latest version works now (or at least last night)

**Comment by nikrolls** [comment]
Perfect, thanks very much @mrabinovsky.

**Comment by nikrolls** [comment]
I'm closing this now as there have been no recent reports of the issue. Feel free to open it again if there is further information.
