### ISSUE TITLE
uBlock-Edge ( minor bugs ) self-explanatory.

### ISSUE THREAD

**Issue by DeathRowRecords** [nikrolls/uBlock-Edge#56]
Hi [nikrolls](https://youtu.be/dQw4w9WgXcQ) 
//[Start](https://youtu.be/1RW3nDRmu6k)/

using SnapsLibrary;

class uBlock_Edge
{
    public void StartProgram()
    {
        SnapsEngine.SpeakString("Hi there. first of all, let me thank you for the cool work you doing. " );
        SnapsEngine.DisplayString("Cough")
        SnapsEngine.Delay(5);
        SnapsEngine.SetTextColor(SnapsColor.Blue);
        SnapsEngine.DisplayString("Thanks");
        SnapsEngine.SpeakString("Thanks");
    }
}

[Feature](https://www.taskus.com/wp-content/uploads/2013/10/typing-dog.gif) 1.
When Enabling "Always clear this when I close the browser" uBlock-Edge zero-out filter list. ( manually update works )

[Feature](http://i.imgur.com/HDEaR.gif) 2.
Resore "Reset to Default Settings" in uBlock not quite how it works :(  ( closing Edge finish the job ) 

Windows 10_X64 Microsoft Edge 38.14393.0.0 uBlock-Edge 1.10.2 [-_-#](http://www.okmoviequotes.com/wp-content/uploads/2014/05/2-Ace-Ventura-Pet-Detective.gif)

ok cool if this helps I'm out . . . [3](http://media.giphy.com/media/RR7aysueE4mTS/giphy.gif) . . . [2](http://www.gifbin.com/bin/reverse-1237811519_chuck-norris-approves.gif) . . . [1](http://i2.kym-cdn.com/entries/icons/original/000/012/982/post-19715-Brent-Rambo-gif-thumbs-up-imgu-L3yP.gif) [Loading](https://static1.squarespace.com/static/52e118dae4b0a7dd7b3c8b76/t/56168f8ce4b0752eb58686b0/1444319183670/dev,+'fuck+it+ship+it'.jpg?format=1500w) . . . 

**Memorable quotes**:

"_A user interface is like a joke. If you have to explain it, it's not that good_" - **Dev Bully**

"_Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth_" - **Marcus Aurelius**

"_It can also be argued that DNA is nothing more than a program designed to preserve itself. Life has become more complex in the overwhelming sea of information. And life, when organized into species, relies upon genes to be its memory system. So, man is an individual only because of his intangible memory... and memory cannot be defined, but it defines mankind. The advent of computers, and the subsequent accumulation of incalculable data has given rise to a new system of memory and thought parallel to your own. Humanity has underestimated the consequences of computerization_" - **Puppet Master**

**Comment by nikrolls** [comment]
Nice spam.

**Comment by DeathRowRecords** [comment]
Wow! sorry 2 hear that :( if u think it was a spam? well . . . letting you
know! Pease be upon you, live long and prosper.
