### ISSUE TITLE
No longer works in Windows 10 15019

### ISSUE THREAD

**Issue by SaiBork** [nikrolls/uBlock-Edge#57]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
After installing the app from the store I get the prompt in Edge to turn it on, which I do. The icon shows up and I can put it next to the address bar, however I am not able to go to the options and clicking the button gives a white square instead of the usual popout window.

Ads are also showing as normal, so it's not just the extension itself not showing properly.

I did the exact same on the 1607 release and that worked fine, so it seems to be something in the latest Windows/Edge build that causes the problem.

### One or more specific URLs where the issue occurs
When trying to go to the options:

Hmmm...can’t reach this page
Try this
Make sure you’ve got the right web address: ms-browser-extension://EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62
Search for "ms-browser-extension://EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62" on Bing
Refresh the page
Details 

Error Code: 0x80004005

### Screenshot in which the issue can be seen
[https://i.imgur.com/w5cbA22.png](https://i.imgur.com/w5cbA22.png)

### Steps for anyone to reproduce the issue
1. Installed app from https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4
2. Started Edge browser
3. Turned on the extension when the popup requests it
4. Left click on the ublock button shows the white popout
5. Right click -> Manage and then clicking on the Options button gets the "Can't reach page" message

### Your settings
- Browser/version: Microsoft Edge in Windows 10 insider build 15019
- uBlock Origin version: 1.10.2

##### Your filter lists
Defaults as I haven't been able to get into any settings yet

##### Your custom filters (if any)
None, see above

**Comment by femfem** [comment]
Extensions for Edge doesn't work in build 15019 as stated under known issues in the release notes [https://blogs.windows.com/windowsexperience/2017/01/27/announcing-windows-10-insider-preview-build-15019-pc](url)

**Comment by SaiBork** [comment]
Fair enough, I'll be honest and say I did not check this builds' notes. I installed the previous one and just updated it yesterday. Thanks femfem.
