### ISSUE TITLE
Add more network block/allowed statistics for enterprise usage

### ISSUE THREAD

**Issue by kurtfalde** [nikrolls/uBlock-Edge#58]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I'm looking at deploying this in an enterprise and wondering if it's possible to get more tracking metric data added as mgmt. always likes more quantifiable statistics.

Specifically it currently appears that the Total Network Requests Allowed / Blocked are stored in reg keys under the user profile

HKEY_USERS\SIDCHANGED_Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\ExtensionsStore\keyvaluestore\keyvaluestore\EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62\settings/allowedRequestCount

HKEY_USERS\SIDCHANGED_Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\ExtensionsStore\keyvaluestore\keyvaluestore\EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62\settings/blockedRequestCount

I'm looking at grabbing the 'value' string value under those 2 keys with our SIEM product but it's going to be some interesting.  I'm not exactly sure what to ask for here but wondering if maybe you could also add a total for the month or week of blocked/allowed requests which we could gather?

Thanks
Kurt

### Your settings

Win10 Anniversary Edition w/ Edge uBlock-Edge pulled from GitHub and packages/signed for local install

##### Your filter lists

N/A

##### Your custom filters (if any)

N/A

**Comment by nikrolls** [comment]
Hi Kurt,

Thanks for getting in touch. I believe Edge is removing the Registry-based storage in the Creators Update being released soon. This is to allow unlimited storage. I'm not sure what the new system they're using is or how accessible it is for other tools to read.

Regarding adding more statistics, this is something that would be dome in the core. @gorhill, your thoughts?

**Comment by nikrolls** [comment]
I'm closing this now as there has been no recent discussion. Feel free to open it again if desired.
