### ISSUE TITLE
Extension fails to work on Windows 10 15042

### ISSUE THREAD

**Issue by vemacs** [nikrolls/uBlock-Edge#59]
I have tried reinstalling uBlock Origin. It appears that no JavaScript is running properly:

![](https://i.imgur.com/F1ti7Uu.png)

![](https://i.imgur.com/KItWCIM.png)

**Comment by vemacs** [comment]
Issue went away after resetting edge: http://www.windowscentral.com/how-to-reset-microsoft-edge-windows-10

**Comment by nikrolls** [comment]
@vemacs, thanks for the update!
