### ISSUE TITLE
[Feature Suggestion] Surface the release info into the Microsoft Store details page release notes.

### ISSUE THREAD

**Issue by arebee** [nikrolls/uBlock-Edge#62]
It would be great to have the git release label flow through into Store entry [release notes](https://docs.microsoft.com/en-us/windows/uwp/publish/create-app-store-listings#default-store-listing-fields).

**Comment by nikrolls** [comment]
Thanks @arebee! Yes, I'm a big fan of the release notes feature in the Store and get annoyed when developers don't use them. Apologies, I either forgot or didn't see the field -- if they're available for Extensions I'll be sure to add them in any future releases.
