### ISSUE TITLE
Can't upload video to Youtube

### ISSUE THREAD

**Issue by kevin12314** [nikrolls/uBlock-Edge#63]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I Can not upload video to YouTube when uBlock Origin is enabled.

### One or more specific URLs where the issue occurs

https://www.youtube.com/upload

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/10508800/23845247/f514cb10-0801-11e7-9cb3-0053402661c0.png)

Turn off uBlock Origin on YouTube still not work
![image](https://cloud.githubusercontent.com/assets/10508800/23845306/450eb770-0802-11e7-93a5-ea96c266c88f.png)

When I disabled uBlock Origin in Microsoft Edge Extensions,it finally works.
![image](https://cloud.githubusercontent.com/assets/10508800/23845613/269956a4-0804-11e7-9834-9481e658b2cd.png)

### Steps for anyone to reproduce the issue

1. Install uBlock Origin in Wndows Store.
2. Go to https://www.youtube.com
3. Login your account
4. Click Upload button on webpage.
5. Choose a video to upload.
6. You will see this issue.

### Your settings

- Browser/version: 
  Microsoft Edge 40.15055.0.0
  Microsoft EdgeHTML 15.15055

- uBlock Origin version: 
 uBlock Origin 1.11.2

##### Your filter lists

Default filter lists
+Adblock Warning Removal List
+Anti-Adblock Killer | Reek
+CHN: CJX's Annoyance List
+CHN: CJX's EasyList Lite (main focus on Chinese sites)
+CHN: EasyList China (中文)
+My filters
@@||onmsft.com^$generichide
avlang2.info##div.tac
ck101.com##div.fuckBlockCover>div.playerCover
cool18.com##div.body_center[style='width:1000px;height:270px;']
#@#.adunit
#@#.block-mbn-offers

##### Your custom filters (if any)
AdBlock Protector ：Listhttps://github.com/X01X012013/AdBlockProtector/raw/master/AdBlockProtectorList.txt

**Comment by gorhill** [comment]
Did you remove `behind-the-scene` from _Whitelist_ pane?

**Comment by kevin12314** [comment]
No. Should I remove it?
![image](https://cloud.githubusercontent.com/assets/10508800/23856170/96a2a23c-0833-11e7-93ad-77014a24bef3.png)

**Comment by gorhill** [comment]
Don't remove it, doing so will cause lots of issue.

Did you look at the logger to see what uBO is doing when you try to upload? (select the _All_ entry in the drop list at the top of the logger).

**Comment by kevin12314** [comment]
Sorry I don't know how to post logs so I take some screenshot.
![image](https://cloud.githubusercontent.com/assets/10508800/23859267/0c8e8916-083e-11e7-86ba-245306593eff.png)
![image](https://cloud.githubusercontent.com/assets/10508800/23859279/16224ae4-083e-11e7-8261-b77fc6dfd827.png)
![image](https://cloud.githubusercontent.com/assets/10508800/23859317/2b0638f8-083e-11e7-9033-eabe6b5ef33e.png)
![image](https://cloud.githubusercontent.com/assets/10508800/23859323/3146d006-083e-11e7-8d26-80d8efc14ef0.png)

**Comment by gorhill** [comment]
The log shows that uBO is not disabled for Youtube. Did you force a reload of the page after disabling uBO?

**Comment by kevin12314** [comment]
Sorry , I didn't turn off uBO in previous post. This one is turn off uBO .
![image](https://cloud.githubusercontent.com/assets/10508800/23860344/9f39f57c-0841-11e7-9fc1-a68b98760531.png)
![image](https://cloud.githubusercontent.com/assets/10508800/23860351/a7776efe-0841-11e7-9597-3e588c9bf2a7.png)
![image](https://cloud.githubusercontent.com/assets/10508800/23860360/aea0588a-0841-11e7-8532-c63cd4393373.png)
![image](https://cloud.githubusercontent.com/assets/10508800/23860375/bc244d68-0841-11e7-92a5-c118fff83cdd.png)
![image](https://cloud.githubusercontent.com/assets/10508800/23860384/c0fd0ad2-0841-11e7-92e2-bd87afd722a7.png)
![image](https://cloud.githubusercontent.com/assets/10508800/23860393/c66e4940-0841-11e7-8991-147ac3eb46ea.png)
![image](https://cloud.githubusercontent.com/assets/10508800/23860399/cbb787cc-0841-11e7-95eb-699c2f35f998.png)

**Comment by gorhill** [comment]
I don't know what the issue is. According to the logger, nothing is being blocked (no need to post the whole thing, what matters is what is being blocked -- the red entries).

**Comment by nikrolls** [comment]
I wonder if this is similar to the issue that stopped all scripts from running on YouTube. It was a browser bug but I found a workaround. I'll investigate.

**Comment by nikrolls** [comment]
In my initial investigation of this issue it appeared to be very similar to the initial issue that stopped scripts running on the YouTube homepages. It's no longer an issue on the latest release of Windows.
