### ISSUE TITLE
Blocked Elements Saved in 'My Filters' Not Working (uBlock Origin For Edge)

### ISSUE THREAD

**Issue by DesertBear** [nikrolls/uBlock-Edge#69]
### Describe the issue
If I block an element with the 'Element Picker', it saves the block rule under 'My Filters', but when MS Edge is re-started, the rules don't work and the blocked elements still appear on the page.

### One or more specific URLs where the issue occurs
https://maps.google.co.uk/
https://www.flickr.com/explore/

### Steps for anyone to reproduce the issue
**1)** Install Microsoft Edge uBlock Origin Extension from the Windows Store

**2)** Go to https://maps.google.co.uk/

**3)** Enter 'Element Picker' mode and select the 'Get Google Chrome' advertisement at the top of the page to block it.  Click the 'Create' button to add the block rule to the 'My Filters' section of uBlock Origin.

**4)** Refresh the page, and the ad is blocked as it should be.

**5)** Close Microsoft Edge, re-open it again and navigate back to https://maps.google.co.uk/.  The element is not blocked anymore, despite the rule still being in the 'My Filters' section and switched on.

**6)** If you try to block the ad again, it just adds the same rule that was added previously.
```
! ‎13‎/‎04‎/‎2017‎ ‎13‎:‎19‎:‎54 https://www.google.co.uk/maps/<snipped>
www.google.co.uk##.gb_g.gb_Nc.gb_Lc.gb_Mc

! ‎13‎/‎04‎/‎2017‎ ‎13‎:‎23‎:‎48 https://www.google.co.uk/maps/<snipped>
www.google.co.uk##.gb_g.gb_Nc.gb_Lc.gb_Mc
```

**Note:**  An alternative URL to try it with is https://www.flickr.com/explore/.  As you scroll, a 'Sign up with Yahoo' box will appear in the bottom-right corner.  If you block this element, it will also re-appear when re-starting Microsoft Edge, despite the block rule in 'My Filters'.

### Screenshot(s)
![001](https://cloud.githubusercontent.com/assets/27423064/25006702/d8413b88-2055-11e7-88d5-0358ee4c7f27.jpg)

![002](https://cloud.githubusercontent.com/assets/27423064/25006701/d83bfc22-2055-11e7-861e-11b8d5595140.jpg)

### Your settings
Windows 10 - 15063.138 (1703)
Microsoft Edge - 40.15063.0.0
Microsoft EdgeHTML - 15.15063
uBlock Origin - v1.11.2

##### Your filter lists
Default filter lists

**Comment by gorhill** [comment]
For Flickr, the solution is a more appropriate filter: `flickr.com##a[data-track="miniSignupFooterSignupClick"]`.

The element picker has its limitations, and sometimes someone with experience in creating filter will be needed. This is such case. The filter choices provided by the element picker were not enough for this specific case, since the page modify the classes of the element to hide just by merely clicking on the element. In such case, opening the inspector and manually crafting the cosmetic filter is how I solved the case.

For the Google Maps page, I am unfortunately not able to reproduce the banner element at the top when using Firefox. I do not have access to Edge, so I can't repro to investigate on my side.

**Comment by japborst** [comment]
Alternatively you could click the "no thanks" button and it won't bother you again. I'll check if i can reproduce it and create a filter

**Comment by DesertBear** [comment]
I'm not sure you fully understand the problem.  The rules that the 'Element Picker' adds work fine, the problem is when closing and re-opening Edge the rules that are saved to 'My Filters' don't work anymore.  

Another example:

Go to https://github.com/nikrolls/uBlock-Edge

**1)** Use the 'Element Picker' to block the 'uBlock Origin Beta for Microsoft Edge' image

**2)** The 'uBlock Origin Beta for Microsoft Edge' image is blocked correctly

**3)** The block rule is added to 'My Filters'

**4)** Close & Re-open Edge, go back to https://github.com/nikrolls/uBlock-Edge .  The image is no longer blocked despite the block rule being in place.  uBlock Origin completely ignores the rule.

**Step 1:**
![001](https://cloud.githubusercontent.com/assets/27423064/25010231/65c65a3c-2061-11e7-8321-4fde97a85ebe.jpg)

**Step 2:**
![002](https://cloud.githubusercontent.com/assets/27423064/25010237/6d907ff4-2061-11e7-9f13-be1ce8baac23.jpg)

**Step 3:**
![003](https://cloud.githubusercontent.com/assets/27423064/25010281/8ae5e292-2061-11e7-90ee-f921135dd054.jpg)

**Step 4:**
![004](https://cloud.githubusercontent.com/assets/27423064/25010286/90184e62-2061-11e7-8a79-da623e5b291f.jpg)

I don't understand what you mean by you don't have access to Edge?  This page is specifically for Edge issues.  https://github.com/nikrolls/uBlock-Edge/issues/

**Comment by m-voit** [comment]
I can confirm the Problem. All my previous used custom filters stopped working when i upgraded to the Creators Update. The only way to change this behavious is making a new custom filter with the element picker. As soon as a new custom filter is added all the filters are working the same way they did before the Creators update.

But when i restart Edge, the filters stop working again until i add a new custom filter.

I am using:

- Microsoft Edge 40.15063.0.0
- Microsoft EdgeHTML 15.15063
- uBlock Origin 1.11.2

**Comment by DesertBear** [comment]
I think the problem is somehow related to the uBlock 3rd-party filters.

Using just the default uBlock Origin 3rd-party filters, when pressing the 'Update Now' button the lists would try to update themselves, but the spinning circles would just keep going and going, even after all internet activity had stopped indicating that they had finished downloading.  The clock icon to indicate the filters were up-to-date would never appear.

Therefore I unchecked 'Malware Domain List', 'Malware domains' and 'Peter Lowe’s Ad and tracking server list', leaving just these ones:

_My filters
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Unbreak
EasyList
EasyPrivacy_

After pressing the 'Update Now' button with just these selected, eventually the spinning circles stopped of their own accord and the clock icons appeared indicating that the filters were up-to-date.  After this, the rules stored in 'My Filters' started working correctly, even after the browser had been closed and re-opened.

Screenshot:
![001](https://cloud.githubusercontent.com/assets/27423064/25053963/7815c78a-2152-11e7-9c75-64cf4b555cc1.jpg)

**Comment by gorhill** [comment]
@DesertBear good findings.

This suggests that issue is related to #4.

As a potential workaround fix, I have modified the order in which lists with no extension are read in <https://github.com/nikrolls/uBlock-Edge/blob/master/assets/assets.json>: now the URL with the extension will be tried before the one with no extension.

**Comment by nikrolls** [comment]
Thanks @DesertBear and @gorhill for looking into this. I'll monitor it along with the next update.

**Comment by DesertBear** [comment]
Today's update to 1.12.1 reset all the settings back to the defaults and subsequently the default third-party lists all loaded correctly.  So although I couldn't see anything in the Release Notes about it, this update appears to have fixed the original issue.  Thanks.
