### ISSUE TITLE
Very slow Edge cold startup

### ISSUE THREAD

**Issue by iandonov** [nikrolls/uBlock-Edge#7]
uBlock v.1.8.5b0
Edge v.39.14901.1000.0

No other extensions installed.

**Comment by nikrolls** [comment]
Hi @iandonov, how long is the extension taking to start up for you?

**Comment by SylveonBottle** [comment]
Due to github's removal of private messages and failure to add any sort of way of contacting you on your page or anywhere, I'll just throw this discussion in this random bug report. No need for me to start a fake bug report on my own for something that could be answered with a single sentence.


I received an email a few weeks ago about how someone requested you upload the add-on to the store, but somebody (probably you) pushed out the idea due to concerns on how strict Microsoft is when adding official addons.

I would just like to alarm you of the fact that Tampermonkey recently submitted a request for their own extension to be added to the Microsoft Store in use with Edge.
The result: https://www.microsoft.com/en-us/store/p/tampermonkey/9nblggh5162s
Notice the "This app is an extension for: Microsoft Edge"


Here's hope for the future of uBlock for Edge!

**Comment by nidunc** [comment]
@SylveonBottle While searching around for more information about [Microsoft Edge's partnership with uBlock Origin][EdgeTwitter], I came across your comment. Even though I'm in no way affiliated with uBlock Origin - I'm but a mere user of the extension - I'd still like to comment on your comment.

Firstly, you mention in your first paragraph that @nikrolls, who forked @gorhill's repository and maintains the Microsoft Edge fork of uBlock Origin on this repository, has failed "to add any sort of way of contacting you *\[him]* on your *\[his]* page or anywhere" (at least, it looks like your comment was directed at Nik Rolls, as you're commenting on his repository). This is in fact not true. If you look at [Nik Rolls' GitHub user page][nikrollsGitHub], you'll see a link to his [about.me page][nikrollsaboutme], on which he links to not only his Twitter account, but also his LinkedIn, Facebook and even his Foursquare account. There are plenty of ways to contact him outside of GitHub.

However, if I look at [Raymond Hill's][gorhillGitHub] (the person who first started developing uBlock, handed it over to Chris Aljoudi and then continued developing uBlock under the name uBlock Origin after Chris pretty much abandoned the project) [GitHub page][gorhillGitHub], I notice that there's no contact information on there, which leads me to believe that your reply was directed at Raymond Hill and not at Nik Rolls. Unfortunately you failed to specify to whom your comment was addressed, so I (and any others reading your comment) can only guess.

Anyway. If you search for "gorhill", you'll come across [his Twitter account][gorhillTwitter], [his Y Combinator Hacker News account][gorhillHackerNews] and most likely also [his website][gorhillwebsite] (on which he links to his Twitter and GitHub account).
So, while Raymond Hill does indeed not list any contact information on his GitHub page, a quick search for his username turns up at least two ways of contacting him. No need to hijack an issue (on a repository that isn't even owned by Raymond Hill and which he probably doesn't, or sporadically, checks).

Secondly, it seems like the developers of Microsoft Edge "are working with uBlock Origin" to bring the extension to Edge. I don't know the details of it, and if they are working with Raymond Hill, Nik Rolls or both of them, but it seems like your comment has been answered by the tweet that I referred to in the first paragraph of my comment.
Of course more details about the partnership would be appreciated, which is what I was looking for, but it seems like uBlock Origin will be coming to the Windows Store in the near future.

Let's hope for the future of uBlock for Edge, indeed.

---

*My apologies for further 'polluting' this issue.*

  [EdgeTwitter]: https://twitter.com/MSEdgeDev/status/779382154249646081 "Microsoft Edge Dev on Twitter: We’re happy to announce that we're working with uBlock Origin, Ghostery, & Turn Off the Lights to bring their extensions to Microsoft Edge!"
  [nikrollsGitHub]: https://github.com/nikrolls "nikrolls (Nik Rolls)"
  [nikrollsaboutme]: https://about.me/nikrolls "Nik Rolls - New Zealand | about.me"
  [gorhillGitHub]: https://github.com/gorhill "gorhill (Raymond Hill)"
  [gorhillTwitter]: https://twitter.com/gorhill "R. Hill (@gorhill) on Twitter"
  [gorhillHackerNews]: https://news.ycombinator.com/user?id=gorhill "Profile: gorhill | Hacker News"
  [gorhillwebsite]: http://www.raymondhill.net/ "Raymond Hill"

**Comment by iandonov** [comment]
Much better now with:
uBlock v1.9.17.6
Edge 39.14971.1000.0

**Comment by nikrolls** [comment]
Thanks for the update @iandonov!
