### ISSUE TITLE
Windows Store Require Insider Program

### ISSUE THREAD

**Issue by ugurozturk** [nikrolls/uBlock-Edge#71]
### Describe the issue
Can't download uBlock Origin from windows store while i am not in insider program. Because the extencion require win 10 15063.0+

### Your settings

- OS/version:  Win 10 14393.1066
- Browser/version: Microsoft Edge 38.14393.1066.0

**Comment by japborst** [comment]
Don't need the insider program, but you'll need to update Windows with the Creators Update.

**Comment by nikrolls** [comment]
Yes, apologies. I didn't quite clarify that in my Twitter announcement 😊
