### ISSUE TITLE
uBlock Origin dashboard not display system language

### ISSUE THREAD

**Issue by kevin12314** [nikrolls/uBlock-Edge#77]
Read first: <https://github.com/nikrolls/uBlock-Edge/blob/master/CONTRIBUTING.md>

### Describe the issue
uBlock Origin dashboard not display system language (traditional Chinese, zh-TW).

I don't know this is Microsoft Edge Bug or uBlock Origin need to update language judgment .

### One or more specific URLs where the issue occurs
ms-browser-extension://EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62/dashboard.html

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/10508800/25420599/6cda9840-2a8b-11e7-89d2-a8c4b3cbff9a.png)

### Steps for anyone to reproduce the issue

1. Install traditional Chinese version Windows 10 or language Packs.
2. If you Install language Packs, go to Setting and change system display language to traditional Chinese (Taiwan).
3. Install uBlock Origin from Windows Store.
4. Open uBlock Origin dashboard , and you will see the display language is English.

### Your settings

- OS/version: Windows 10 Build 15063
- Browser/version: Microsoft Edge 40.15063.0.0
- uBlock Origin version: uBlock Origin 1.12.1

**Comment by nikrolls** [comment]
Thanks @kevin12314, I'm looking in to it.

**Comment by kevin12314** [comment]
In Windows 10 Build 16294 and Build 16362, uBlock Origin dashboard is now display system language, but you need to reinstall uBlock Origin.
This issue can be closed.
