### ISSUE TITLE
What is Status of uBlock Origin on Microsoft Store ? - Currently There is No Access

### ISSUE THREAD

**Issue by HJLBX** [nikrolls/uBlock-Edge#78]
What is the status of uBlock Origin on the Microsoft Store ?

It is requiring an Insider's enrollment.  Even if you do sign up for Insider builds, there is still no access to uBlock Origin for Edge... the Get App button remains "greyed out"\inaccessible.

**Comment by nikrolls** [comment]
uBlock Origin is available on Edge for those running the Windows 10 Creators Update. This is because it relies on features and fixes that are only present in the CU. Insider builds are not required.

If you have not yet received the update to CU, you can trigger it manually at the [Software Download Site](https://aka.ms/eojpj8).

**Comment by nikrolls** [comment]
Referring to #79: @HJLBX, where do you see that the CU rollout has been halted? Are you not able to update via the link I provided?

**Comment by HJLBX** [comment]
CU is not coming through Windows Update due to the problems reported by users.  On Insider's it stopped coming through last night.  I am already enrolled in the Insider's program.  I tried the link as shown in the Microsoft Store, but there is no access.  Microsoft began warning users a week ago not to install CU - at least not manually at first.  Whatever they've done in the meantime, CU isn't coming through standard Windows Update nor the Insider's Program as of last night.  If you can get CU to download via the Insider Program, it will fail to install.  I tried on two MSI desktops, a Dell XPS 15, and two Toshiba laptops.  5 failed CU installs on 5 different systems is no coincidence.

**Comment by nikrolls** [comment]
That's not what the article says. The issue they mention is with a specific set of Bluetooth radios which they have blocked temporarily. All other systems can get the update, as can anyone who triggers the update manually (though they may have issues).

Unfortunately there's nothing I can do about any of this. uBlock requires features and fixes that are only in the Creators Update, and if I make it available to people on the Anniversary Update I will get complaints of it not working properly. Creators Update will reach everyone eventually, so we just need to wait.
