### ISSUE TITLE
Reading mode fails even if whitelisted

### ISSUE THREAD

**Issue by Jekyll4k** [nikrolls/uBlock-Edge#81]
### Description
The built in reading mode will fail to load the whole content even if the site is whitelisted. This doesn't happen if the plugin is disabled. Whitelisting should prevent any interaction.

Also, it appears that when the plugin is enabled and you switch to reading mode, opening the developer tools and closing it fixes this issue for some reason.

### URLs where the issue occurs
http://www.hrr-strafrecht.de/hrr/1/11/1-273-11.php
http://www.zeit.de/digital/datenschutz/2017-05/wannacry-ransomware-cyberattacke-bitcoin-windows-microsoft

### Reproduction
1. Open the URL.
2. Add to whitelist and reload (optional)
2. Switch to reading mode.
3. Scroll down, there is content missing.
4. Open developer tools.
5. Close developer tools 
6. Missing content will be there.

### My settings
- Win 10 Version 1703 (Build 15063.296)
- Microsoft Edge 40.15063.0.0
- Microsoft EdgeHTML 15.15063
- uBlock Origin version: 1.12.1

##### My filter lists
Default filter lists + 
Anti-Adblock Killer | Reek + 
Fanboy’s Annoyance List + 
Fanboy’s Social Blocking List

I do not use any other add-ons.

**Comment by nikrolls** [comment]
@Jekyll4k Could you please check if this is still an issue with the latest version?

**Comment by nikrolls** [comment]
Closing this due to a lack of activity and being unable to reproduce the issue.
