### ISSUE TITLE
Edge easylist filter requesting to download .htm in youporn.com

### ISSUE THREAD

**Issue by dhigh88** [nikrolls/uBlock-Edge#86]
### Describe the issue
It's been a long time this has been happening ; I maybe thought filter updates would fix this issue as youporn.com is still affected when the Easylist filter is enabled in Microsoft Edge. The website won't open but rather request to download the page. This issue was fixed with several sites when the Creators Update was released but it came back just with youporn for some reason.

[URL(s) for issue on a specific site are **mandatory**
youporn.com

### Screenshot in which the issue can be seen

![27614748-b3423c18-5b71-11e7-92da-450a720db7f4](https://user-images.githubusercontent.com/26260953/27722084-0bd2414e-5d33-11e7-9663-5d351b233dab.jpg)

### Steps for anyone to reproduce the issue

1. Have Easylist enabled
2. Go to www.youporn.com (NSFW)
3. Microsoft Edge doesn't load the page, rather request to download it as an htm.

### Your settings

- OS/version: Microsoft Windows 10 1703 15063.413
- Browser/version: Microsoft Edge 40.15063.0.0
- uBlock Origin version: 1.12.4

##### Your filter lists

Default

##### Your custom filters (if any)
None

**Comment by dhigh88** [comment]
@okiehsch please help?.

**Comment by dhigh88** [comment]
@nikrolls hello?

**Comment by okiehsch** [comment]
What do you want me to do? 
I do not have `Microsoft Windows 10 1703` installed, so I can't help you.

**Comment by dhigh88** [comment]
@okiehsch My bad. I thought since you were part of the ublock origin assistance team you could have helped me. The ublock edge issues are silent and nikrolls has been absent since a month with no updates.
