### ISSUE TITLE
uBlock-Edge version

### ISSUE THREAD

**Issue by ghost** [nikrolls/uBlock-Edge#87]
### Describe the issue
uBlock-Edge version

### One or more specific URLs where the issue occurs

None

### Screenshot in which the issue can be seen

![ublock_origin_edge_github](https://user-images.githubusercontent.com/17460623/27751145-38c162ea-5ddb-11e7-96aa-ebac9522874a.gif)

### Steps for anyone to reproduce the issue

1. Click on the burger
2. uBlock-Edge
3. And behold

### Your settings

Default

- OS/version: W10 version 1703 ( OS Build 15063,447 ) 
- Browser/version: Microsoft Edge 40.15063.0.0 Microsoft EdgeHTML 15.15063
- uBlock Origin version: 1.12.4
 
##### Your filter lists

Default filter lists 

##### Your custom filters (if any)
None

##### Miscellaneous

Pixies - Where is my Mind

**Comment by dhigh88** [comment]
LoL tell me about it... It's really getting frustrating posting issues in here when nobody helps at all. The creator nikrolls hasn't been active since May.  The latest version is 1.13.4, and no idea when that'll be available. Really giving up here. The Ublock origin page has been very active as Gorhill is amazing at assisting quickly.  smh...

**Comment by DeathRowRecords** [comment]
@dhigh88 XD I was about to hit you with this comment "That's just disgusting" and suggest pornohub.su :P well about @nikrolls dunno maybe he depress or some kind of kinky sh!t mental block but he Good Man ( Maintainer ) give him some time :) but sometimes I like 2 troll him 4 no apparent reason. But yeah I need that ZAP DOM Element thing in uBlock 1.13.4. All the Best Dude with the Bug :P

**Comment by ghajini** [comment]
Edge version is stuck because there are too many bugs in Microsoft edge browser and don't have necessary api for that.....once bugs are fixed there will be active development of ublock edge I think

**Comment by nikrolls** [comment]
The extension is up to date again and will be actively maintained. I apologise for my absence.
