### ISSUE TITLE
Windows store error for Windows 10 Pro version

### ISSUE THREAD

**Issue by lgomezbl** [nikrolls/uBlock-Edge#88]
Read first: <https://github.com/nikrolls/uBlock-Edge/blob/master/CONTRIBUTING.md>

### Describe the issue
When I try to install Windows Store request OS version 15063.0 (latest version is 14393.1480 for Windows 10 Pro).

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]https://www.microsoft.com/store/apps/9nblggh444l4
### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/3873625/28571735-4baca424-7112-11e7-8229-b288c280a1d0.png)
![image](https://user-images.githubusercontent.com/3873625/28571788-79f6b6d0-7112-11e7-8c0b-fa39243ed23c.png)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
2. Because we are not looking over your shoulder and
3. Keep in mind: Nobody can read your mind.

This occur during installation process from Windows Store.
### Your settings

[If you fail to provide this info, the issue will be marked as invalid. Lists all settings which differ from default]

- OS/version: Windoiws 10 Pro
- Browser/version: Windows Edge
- uBlock Origin version: Current published in Windows Store

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by reunicorn** [comment]
You do not have the latest update, which is required for use of uBlock-Edge 1.13.8:

The latest update for Windows 10 Pro is 15063.483, also known as the Creators Update. You can download the update by going to the [Download Windows 10](https://www.microsoft.com/en-us/software-download/windows10) page and clicking [Update Now](http://go.microsoft.com/fwlink/?LinkID=799445).

![w10pro](https://user-images.githubusercontent.com/9095637/28600083-a2591260-7164-11e7-888c-5196c723926e.PNG)

**Comment by nikrolls** [comment]
Thanks @reunicorn. This is the issue. As many of the fixes in Creators Update are required for uBlock to work, you must have this update to install it.

**Comment by lgomezbl** [comment]
Thanks!
