### ISSUE TITLE
Massive memory usage while updating filter lists

### ISSUE THREAD

**Issue by TheRyuu** [nikrolls/uBlock-Edge#9]
I'm not sure whether this is a consequence of how the Edge version has to handle larger objects by splitting them but I'm seeing Edge use HUGE amounts of memory in what I believe is its main rendering process.

The amount of memory consumed seems to grow the more filter lists that are enabled.  With all non-language specific filter lists enabled (except for reek's anti-adblock list and the redundant lists (such as easylist without element hiding and Fanboy's ultimate list)) I see upwards of 4-6GB of memory usage out of the main browser process while doing a purge and update if all the lists.

The process of updating the lists also appears to be much slower than in Chrome and will be burning through CPU while the memory usage climbs.  On one purge cache and update I've seen nearly 8GB's of memory usage.

This really shouldn't have to be said but this is on W10 64-bit w/RS1 (AU) with the current HEAD of the master branch as of writing.  Furthermore this issue only appears during filter lists updates and is most noticeable after a purge caches and full update of all the lists.  It does not manifest in day to day usage with auto-update disabled and the main browser process has "normal" memory usage of ~100MB (maybe slightly more).  I have not used it with auto-update enabled.

**Comment by nikrolls** [comment]
Thanks @TheRyuu, I'll look into it. Your theory could indeed be correct as this is not an ideal way to handle it, however at the same time there are very few alternatives (possibly even none).

**Comment by nikrolls** [comment]
@TheRyuu, I'd be interested in your feedback on whether this is still an issue now that we're handling storing filter lists in a much more efficient manner.

**Comment by nikrolls** [comment]
I'm going to close this because I've had independent reports that the efficiency issues are resolved now. It can be re-opened if necessary.
