### ISSUE TITLE
Popup UI broken in recent Insider Builds

### ISSUE THREAD

**Issue by ansorg** [nikrolls/uBlock-Edge#90]
Read first: <https://github.com/nikrolls/uBlock-Edge/blob/master/CONTRIBUTING.md>

### Describe the issue
uBlock Popup-UI is broken in Edge in recent insider Builds (as of today: 16257, but seen one or two builds before already). The list of stuff to block is empty. Although according to the statistics on the right blocking itself does work.

### One or more specific URLs where the issue occurs
everywhere

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/3541784/29507421-53dcff7e-8650-11e7-96a5-a6fe1bf488fe.png)

### Steps for anyone to reproduce the issue

install uBlock-Edge from Store on Windows Build 16257, check the add-in in Edge

### Your settings

W10Pro Insider 16257
Edge 41.16257.1.0
uBlock Origin 1.13.8, default settings + "experienced user"

##### Your filter lists
Default

**Comment by stkb** [comment]
Seems similar to #70 which I was wondering if it had been fixed in insider. Looks like it's now a slightly different problem but still no good for advanced mode. :(

**Comment by ansorg** [comment]
No, I think #70 is something different. I experience #70 all the time, especially annoying on tablet with pure touch, no mouse hover. 

But this is new, if the popup shows full size, the left area, where the list of all resources should be, is completely blank.

**Comment by raaomoka** [comment]
> Has this got worse for anyone else since the latest version since the latest version (1.13.8)? For me the window never opens up fully

I'm experiencing the exact same issue on my Surface Pro 2 with Windows 10 Creators Update (v1703 B 15063.608):

![ublock origin floating window not opening fully 2017 09 15](https://user-images.githubusercontent.com/2476232/30509694-ebcf58ea-9a73-11e7-9615-7e91b1a77e69.png)

Edge seriously needs to start getting updates from the windows store to fix these compatibility issues fast. Chrome had its crash haven and compatibility-breaking days, but at least it was updated fast and independent of the OS. Whereas fkn edge is keeping users frustrated for half a year before it gets updated. Oh well, the longer they wait, the more it becomes merely a stupidly unreliable browser to download other browsers, just like IE.

**Comment by IcePanther** [comment]
Same problem as @raaomoka here, popup almost always open to small size despite listing elements, consistent behavior on several machines with Intel and nVidia GPUs, all on Windows 10 Fall Creator's Update.

I have to click again and again and hope that it opens correctly, very annoying and pretty much destroys dynamic filtering usability. Seems linked to issue #70 too.

**Comment by nikrolls** [comment]
Recent insider builds have resolved this except for advanced mode. There is a fix for advanced mode in #103 that we're working on, and issue is being tracked in #95.
