### ISSUE TITLE
Store whitelist in roaming profile

### ISSUE THREAD

**Issue by GeertvanHorrik** [nikrolls/uBlock-Edge#93]
### Describe the issue

When using multiple devices, it would be nice if the sites I've whitelisted would roam. I am not sure if edge allows the same easy of use for roaming settings as UWP?

### Your settings

- OS/version: Any
- Browser/version: Any
- uBlock Origin version: v1.13.8

**Comment by nikrolls** [comment]
uBlock cloud storage support will allow your settings to roam across browsers with which you're logged in with the same MSA as your primary account. However to the way uBlock handles cloud storage, it requires you to click the button to pull down the latest changes every time there is something new. Does this suit your requirement?

**Comment by GeertvanHorrik** [comment]
I think it would be better if this would be automated, syncing in general should be an automated process. If I want to exclude a specific machine from synchronization, I can simply disable it.

Or.... the setting could be:

- Disable
- Enable - auto
- Enable - manual

**Comment by nikrolls** [comment]
@GeertvanHorrik I can see the value in that. Those changes would have to be discussed in the core repository however: https://github.com/gorhill/uBlock/issues

**Comment by nikrolls** [comment]
Closing this as the request is to do with core functionality and not something that can be changed in just one platform.
