### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by tobiaskohlbau** [nikrolls/uBlock-Edge#94]
@nikrolls could you leave a comment on the project status?
If it's not possible for you out of any reasons to support this repo any further would you be open to one of the following ideas:

1. Hand over the project to some other maintainer.
2. Merge this branch back into [gorhill/uBlock](https://github.com/gorhill/uBlock).

For the second part I would like to hear comments by gorhill if he is willing to accept the edge specific part in his repository and maybe submitting it into the Microsoft Store under his name like with Chrome or Firefox, which would lead to less fragmentation IMHO.

I've done a fork and merged [gorhill/uBlock](https://github.com/gorhill/uBlock) into it and by the looks there are no merge issues and no files where changed outside edge specific parts. In addition I've build a local version of the extension which works like expected.

```
$ git diff --name-status 1.14.14 master
A       platform/edge/about.html
A       platform/edge/img/browsericons/icon19-off.png
A       platform/edge/img/browsericons/icon19.png
A       platform/edge/img/browsericons/icon38-off.png
A       platform/edge/img/browsericons/icon38.png
A       platform/edge/is-webrtc-supported.html
A       platform/edge/is-webrtc-supported.js
A       platform/edge/managed_storage.json
A       platform/edge/manifest.json
A       platform/edge/options_ui.html
A       platform/edge/options_ui.js
A       platform/edge/polyfill.js
A       platform/edge/vapi-background.js
A       platform/edge/vapi-client.js
A       platform/edge/vapi-common.js
A       tools/make-edge.sh
```

cc @gorhill

**Comment by DeathRowRecords** [comment]
@gorhill i really do respect your work the immeasurable amount of time and effort you put into well define world wide historically project which is uBlock Origin astound me! I undertake the accomplishment of your enthusiasm and great high energy presents in contributors swiftness action that indicates direction into motion of immense work. Building Great Legacy has the right ingredients, but the drawback is bad timing. As a Strong Vigilant Hero who recognize the hostile threat and spawn innovative intelligence solutions to Oppose to Resist to Disobey Withstand the destructive handicap forces who may emerge and become evident from concealment . . . Therefore having been assigned and consequently responsible here of written words and emphasize to @tobiaskohlbau position of its corresponding problem ( left it for two days without a comment ) "I" Urge you to speak freely flawlessly in a distinct manner. But as we well know Mr @gorhill appearances can be deceiving, my real set of agenda is the lack of reply. I suddenly have retain ( something ) in my memory that left me a bad taste in my mouth, and it wasn't pleasant. And i bid you . . . good day to you sir!.

**Comment by gorhill** [comment]
I don't see what I can do. This all rest on @nikrolls coming here. Without this, the project is completely stale for Microsoft Edge users. Maybe prepare a fully reviewed/working pull request so that uBO is upgraded to the latest version, then it would be just a matter of merging the changes. The other aspect, having to push to the store can still be a burden for a volunteer when one has just no time, so in that case we would have to find a new volunteer to take care of that aspect. But even with a fully working pull request and a new trusty volunteer, nothing can move forward without @nikrolls at least transferring ownership of the Microsoft Store entry.

**Comment by jspenguin2017** [comment]
The name is taken and we need him to be back either way, if he comes back, he can just merge the changes himself. Although if @gorhill reach out to Microsoft he might be able to take the ownership forcefully. 

I'm looking to port Nano to Edge, apparently Nano's icon is too big for Edge and it doesn't recognize it, I think beside that, patching 2 or 3 APIs should get it up and running. The way @nikrolls patched it makes it kind of hard to pull upstream change, but at the end, it's up to him. I think it's better to copy `browser` to `chrome` then monkey-patch it. 

Another problem is Microsoft thinks their extension store is full although there are only 70 extensions in there, if Nano works on Edge, it will be manual install only.

**Comment by nikrolls** [comment]
My most sincere apologies for my absence. I never intended to let this lapse, but life events got in the way. I'm back on board now.
