### ISSUE TITLE
Menu not visible in Edge if Advanced is enabled

### ISSUE THREAD

**Issue by ToniCipriani** [nikrolls/uBlock-Edge#95]
Filter issues MUST NOT be reported here. Read first: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

Describe the issue

See screenshot, Menu is not resized to the wider view when Advanced is enabled

One or more specific URLs where the issue occurs

Not Applicable
[URL(s) for issue on a specific site are mandatory]

Screenshot in which the issue can be seen

https://i.imgur.com/4Xa3T6x.png
[Screenshot(s) for visual issues are mandatory]

Steps for anyone to reproduce the issue

Open extension menu in Edge
Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

OS/version: Windows 10.16299.19
Browser/version: Edge 41.16299.15
uBlock Origin version: 1.13.18
Your filter lists

Not Applicable
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

Your custom filters (if any)

**Comment by davidjade** [comment]
I am seeing this with Advanced mode open almost 100% of the time. It seems to just get the size of the popup UI wrong. It seems like it starts showing the compact UI as I see a brief flash of it, then switches to the wide UI but doesn't resize when that happens.

**Comment by nikrolls** [comment]
@Hsn723 has a fix for this, I'm just working with @gorhill to see if it can go in the core as it's in a file that is not yet per-platform. As soon as that's decided this will be fixed.

**Comment by stephpoo233** [comment]
Fix this back now I would appreciate it


Sent from Mail for Windows 10

**Comment by stephpoo233** [comment]
Fix this thasnk you


Sent from Mail for Windows 10
