### ISSUE TITLE
uBlock Origin interrupts loading on xvideos player

### ISSUE THREAD

**Issue by gguuvvoo** [nikrolls/uBlock-Edge#96]
Read first: <https://github.com/nikrolls/uBlock-Edge/blob/master/CONTRIBUTING.md>

### Describe the issue
Exact same problem described here: https://github.com/nikrolls/uBlock-Edge/issues/80 but with Firefox 57 and 57.0.1. Videos on www.xvideos.com show error message: "Loading error". So far this is the only website I have visited where this issue happens.
This issue started to occur after upgrading to Firefox Quantum (Firefox 57) and continued after the upgrade to Firefox 57.0.1.

### One or more specific URLs where the issue occurs
https://www.xvideos.com/video31655595/brandi_love_gets_creampie
https://www.xvideos.com/video28425741/thick_milf_goes_after_teen#

### Screenshot in which the issue can be seen

![screenshot](https://user-images.githubusercontent.com/34154780/33491287-581944ec-d67f-11e7-9d25-0825332565ac.png)

### Steps for anyone to reproduce the issue

1. Have the uBlock Origin WebExtension installed on Firefox 57 or 57.0.1 with default settings.
2. Click on any random video at www.xvideos.com.
3. Wait for the error message "Loading error" and the "Retry" button.
4. As soon as the uBlock Origin WebExtension gets disable using Ctrl+Click www.xvideos.com works as intended.

### Your settings

Default uBlock Origin settings, nothing has been changed since I installed the WebExtension.

- OS/version: Windows 10 Pro 64 Bits, Version 1709, Compilation 16299.64
- Browser/version: Firefox 57.0.1 (64 Bits)
- uBlock Origin version:  1.14.20

##### Your filter lists

Default filter lists

##### Your custom filters (if any)
N/A

**Comment by nikrolls** [comment]
@gguuvvoo: This is the repository for the Microsoft Edge version of uBlock. Please file reports for Firefox at https://github.com/gorhill/uBlock/issues. Futhermore, this issue does not seem to be present on Edge.
